### ISSUE TITLE
faux-mgs panic while attached to scrimlet console

### ISSUE THREAD

**Issue by jordanhendricks** [oxidecomputer/management-gateway-service#122]
(Not certain if this is the correct repo; feel free to redirect as appropriate)

In today's dogfood update, we saw faux-mgs crash while connected to the console of a scrimlet:

Around when it crashed. Note the attempt to connect to the console again failed:
```
BRM42220051 # zpool list
NAME                                       SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
oxi_24d4ec6c-041a-4c79-abe9-c86316b68534   748G   644M   747G        -         -     0%     0%  1.00x    ONLINE  -
oxi_5a058adc-8208-4bff-b4f3-44e2651435b0   748G   644M   747G        -         -     0%     0%  1.00x    ONLINE  -
oxp_021afd19-2f87-4def-9284-ab7add1dd6ae  2.91T  46.3G  2.86T        -         -     0%     1%  1.00x    ONLINE  -
oxp_11b02ce7-7e50-486f-86c2-de8af9575a45  2.91T  13.8G  2.89T        -         -     0%     0%  1.00x    ONLINE  -
oxp_2d1ebe24-6deb-4f81-8450-6842de28126c  2.91T  63.4G  2.84T        -         -     1%     2%  1.00x    ONLINE  -
oxp_350b2814-7b7f-40f1-9bf6-9818a1ef49bb  2.91T  4.48M  2.91T        -         -     0%     0%  1.00x    ONLINE  -
oxp_4a624324-003a-4255-98e8-546a90b5b7fa  2.91T  31.5G  2.88T        -         -     0%     1%  1.00x    ONLINE  -
oxp_6b9ec5f1-859f-459c-9c06-6a51ba87786f  2.91T  35.0G  2.87T        -         -     0%     1%  1.00x    ONLINE  -
oxp_91ea7bb6-2be7-4498-9b0d-a0521509ec00  2.91T  39.3G  2.87T        -         -     0%     1%  1.00x    ONLINE  -
oxp_e12f29b8-1ab8-431e-bc96-1c1298947980  2.91T  9.21G  2.90T        -         -     0%     0%  1.00x    ONLINE  -
oxp_e6d2fe1d-c74d-40cd-8fae-bc7d06bdaac8  2.91T  70.3G  2.84T        -         -     0%     2%  1.00x    ONLINE  -
rpool                                     3.94G   773M  3.18G        -         -    11%    19%  1.00x    ONLINE  -
BRM42220051 # thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RPC call failed (gave up after 5 attempts)', faux-mgs/src/usart.rs:86:58
                                                 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error: failed to send data (task shutdown?)

Caused by:
    channel closed
jordan@jeeves ~ $ pilot sp console BRM42220051
attaching to console; to detach, press: Ctrl-A, Ctrl-X...
 creating SP handle on interface rack2sw0tp1, component: faux-mgs
                                                                 Sep 07 18:33:19.382 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:185%7]:11111, interface: rack2sw0tp1, component: faux-mgs
                                                                              Error: failed to attach to serial console

Caused by:
    0: Error response from SP: serial console already attached
    1: serial console already attached
```

Forcing a detach of the previous session allowed us to proceed on the console again:

```
jordan@jeeves ~ $ pilot sp console -D BRM42220051
attempting to detach console prior to attaching...
Ok("SP serial console detached\n")
attaching to console; to detach, press: Ctrl-A, Ctrl-X...
faux-mgs
        Sep 07 18:33:52.064 INFO initial discovery complete, addr: [fe80::aa40:25ff:fe04:185%7]:11111, interface: rack2sw0tp1, component: faux-mgs
```

**Comment by jgallagher** [comment]
This should be better after #124; in particular, the underlying cause of this error:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RPC call failed (gave up after 5 attempts)', faux-mgs/src/usart.rs:86:58
```

no longer panics, and instead will produce a warning, and if the SP becomes responsive again it should recover.

If faux-mgs crashes or generally exits without cleanly detaching, having to force a detach to reattach is expected; I'm not sure of a way to make this better. There are some conditions in which the SP will time out the old, stale connection (in which case you wouldn't have to force detach to reconnect), but not all, and the timeout is probably long enough that if you hit this in an active session you won't really want to wait for it.

**Comment by jordanhendricks** [comment]
Thanks @jgallagher! FWIW I don't think it's a big deal to have to force the detach; mostly wanted to document that as the workaround.
